/* Light And Shadow. A Persistent Universe based on Robert Jordan's Wheel of Time Books.
 * Copyright (C) 2001-2002 WOTLAS Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package wotlas.editor;

import wotlas.client.screen.plugin.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;

import wotlas.utils.*;
import wotlas.libs.aswing.*;

import wotlas.libs.persistence.*;
import wotlas.common.*;

import wotlas.utils.Debug;

import wotlas.common.universe.*;

import wotlas.client.*;
import wotlas.client.screen.*;


/** Plug In to add editor tools
 *
 * @author Aldiss, Fred McMaster, Diego
 */

public class EditorPlugIn extends JPanelPlugIn {
 /*------------------------------------------------------------------------------------*/ 
  
  /** 'New' map button.
   */
    transient private AButton newMapButton;

  /** 'Save' map button.
   */
    transient private AButton saveMapButton;

  /** Center panel where the macros are set...
   */
    transient private JPanel centerPanel;
    
    
    /** Creates new form EditorPlugIn2 */
    public EditorPlugIn() {
        super();
        initComponents();
        init();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        ButtonNew = new javax.swing.JButton();
        ButtonSave = new javax.swing.JButton();
        ButtonLoad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DataID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DataFullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DataShortName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DataInsertionPoint = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DataSmallImage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DataMusicName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DataGroupOfGraphics = GetNewGOGList();
        jLabel9 = new javax.swing.JLabel();
        DataLength = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DataHeight = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DataMapSize = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        DataBasicSetId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DataBasicSetIdNr = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jList1 = GetNewGOGList();
        jPanel6 = new javax.swing.JPanel();
        SetDefaultTile = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonNew.setText("New");
        ButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewActionPerformed(evt);
            }
        });

        jPanel1.add(ButtonNew);

        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        jPanel1.add(ButtonSave);

        ButtonLoad.setText("Load");
        ButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoadActionPerformed(evt);
            }
        });

        jPanel1.add(ButtonLoad);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editor Tools");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jTabbedPane1.setName("");
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTree1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(12, 2));

        jLabel2.setText("Id");
        jPanel4.add(jLabel2);

        DataID.setText("jTextField1");
        jPanel4.add(DataID);

        jLabel3.setText("Full Name");
        jPanel4.add(jLabel3);

        DataFullName.setText("jTextField2");
        jPanel4.add(DataFullName);

        jLabel4.setText("Short Name");
        jPanel4.add(jLabel4);

        DataShortName.setText("jTextField3");
        jPanel4.add(DataShortName);

        jLabel5.setText("Insertion Point");
        jPanel4.add(jLabel5);

        DataInsertionPoint.setText("jTextField4");
        jPanel4.add(DataInsertionPoint);

        jLabel6.setText("Small Image");
        jPanel4.add(jLabel6);

        DataSmallImage.setText("jTextField5");
        jPanel4.add(DataSmallImage);

        jLabel7.setText("Music Name");
        jPanel4.add(jLabel7);

        DataMusicName.setText("jTextField6");
        jPanel4.add(DataMusicName);

        jLabel8.setText("Group Of Graphics");
        jPanel4.add(jLabel8);

        jPanel4.add(DataGroupOfGraphics);

        jLabel9.setText("Length");
        jLabel9.setToolTipText("null");
        jPanel4.add(jLabel9);

        DataLength.setText("jTextField7");
        jPanel4.add(DataLength);

        jLabel10.setText("Height");
        jPanel4.add(jLabel10);

        DataHeight.setText("jTextField8");
        jPanel4.add(DataHeight);

        jLabel11.setText("Map Tile Size");
        jPanel4.add(jLabel11);

        jPanel4.add(DataMapSize);

        jLabel12.setText("Basic Tile Set Id");
        jPanel4.add(jLabel12);

        DataBasicSetId.setText("jTextField9");
        jPanel4.add(DataBasicSetId);

        jLabel13.setText("Nr. basic image");
        jPanel4.add(jLabel13);

        DataBasicSetIdNr.setText("jTextField10");
        jPanel4.add(DataBasicSetIdNr);

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel5.add(jList1, java.awt.BorderLayout.CENTER);

        SetDefaultTile.setText("Set Default Tile");
        jPanel6.add(SetDefaultTile);

        jPanel6.add(jPanel7);

        jPanel5.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("tab3", jPanel5);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void ButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoadActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_ButtonLoadActionPerformed

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void ButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewActionPerformed

        
        
    }//GEN-LAST:event_ButtonNewActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList DataGroupOfGraphics;
    private javax.swing.JButton SetDefaultTile;
    private javax.swing.JTextField DataFullName;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton ButtonLoad;
    private javax.swing.JTextField DataBasicSetIdNr;
    private javax.swing.JTextField DataHeight;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JList DataMapSize;
    private javax.swing.JTextField DataShortName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField DataBasicSetId;
    private javax.swing.JTextField DataLength;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField DataSmallImage;
    private javax.swing.JList jList1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton ButtonNew;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField DataMusicName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField DataID;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField DataInsertionPoint;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTree jTree1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
 /*------------------------------------------------------------------------------------*/

  /** Called once to initialize the plug-in.
   *  @return if true we display the plug-in, return false if something fails during
   *          this init(), this way the plug-in won't be displayed.
   */
    public boolean init() {
        WotlasLocation location = new WotlasLocation();
        TileMap tileMap = EditTile.getDataManager().getWorldManager().getTileMap( location );
        DataID.setText("xxx");
        DataFullName.setText(tileMap.getFullName());
        DataShortName.setText(tileMap.getShortName());
        DataInsertionPoint.setText("xxx");
        DataSmallImage.setText("xxx");
        DataMusicName.setText(tileMap.getMusicName());
        //  doing this lose the right object
        // DataGroupOfGraphics = GetNewGOGList();
        DataLength.setText( "" + tileMap.getMapSize().width );
        DataHeight.setText( "" + tileMap.getMapSize().height );
        // DataMapTileSize.setText();
        DataBasicSetId.setText( "" + tileMap.getManager().getBasicFloorId() );
        DataBasicSetIdNr.setText( "" + tileMap.getManager().getBasicFloorNr() );
        return true; // this plug-in always works...
    }

 /*------------------------------------------------------------------------------------*/

    /** Called when we need to reset the content of this plug-in.
    */
    public void reset() {
        // We remove the previous content
    	init();
    }

   /** Returns the name of the plug-in that will be displayed in the JPlayerPanel.
    * @return a short name for the plug-in
    */
      public String getPlugInName() {
      	  return "Editor";
      }

 /*------------------------------------------------------------------------------------*/

   /** Returns the name of the plug-in's author.
    * @return author name.
    */
      public String getPlugInAuthor() {
          return "Wotlas Team (Aldiss & Fred & Diego)";
      }

 /*------------------------------------------------------------------------------------*/

   /** Returns the tool tip text that will be displayed in the JPlayerPanel.
    * @return a short tool tip text
    */
      public String getToolTipText() {
          return "To create/change TileMap";
      }

 /*------------------------------------------------------------------------------------*/

   /** Eventual index in the list of JPlayerPanels
    * @return -1 if the plug-in has to be added at the end of the plug-in list,
    *         otherwise a positive integer for a precise location.
    */
      public int getPlugInIndex() {
          return -1;
      }

 /*------------------------------------------------------------------------------------*/

   /** Tells if this plug-in is a system plug-in that represents some base
    *  wotlas feature.
    * @return true means system plug-in, false means user plug-in
    */
    public boolean isSystemPlugIn() {
        return false;
    }
      
    public JList GetNewGOGList() {
      	JList list = new JList();
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("Demo Set");
        listModel.addElement("Rogue Like");
        list = new JList(listModel);
        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        list.setSelectedIndex(0);
//        list.addListSelectionListener(this);
        list.setVisibleRowCount(5);
//        JScrollPane listScrollPane = new JScrollPane(list);
        return list;
    }
}
