/*
 * Light And Shadow. A Persistent Universe based on Robert Jordan's Wheel of Time Books.
 * Copyright (C) 2001-2002 WOTLAS Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package wotlas.libs.graphics2d.menu;

import java.util.EventObject;

/** An event generated by a menu when an item has been clicked. The source of the
 *  event is a string with the following format : "menu-name:item-name".
 *
 * @author Aldiss
 * @see wotlas.libs.graphics2d.menu.Menu2DListener
 */

public class Menu2DEvent extends EventObject {

    /*------------------------------------------------------------------------------------*/

    /** Menu that fired the event.
     */
    protected Menu2D menu2D;

    /** Name of the item that fired the event.
     */
    protected String itemName;

    /*------------------------------------------------------------------------------------*/

    /** Constructor with the source of the event : menu/item.
     *
     *  @param menu2D menu source of the event
     *  @param itemName item source of the event
     */
    public Menu2DEvent(Menu2D menu2D, String itemName) {
        super("" + menu2D.getName() + ":" + itemName);
        this.menu2D = menu2D;
        this.itemName = itemName;
    }

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/

    /** To get the source of the event as a string object.
     *  @return a string with the following format : "menu-name:item-name".
     */
    @Override
    public String toString() {
        return "" + this.menu2D.getName() + ":" + this.itemName;
    }

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/

    /** To get the menu source of the event.
     *  @return menu.
     */
    public Menu2D getMenu2D() {
        return this.menu2D;
    }

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/

    /** To get the name of the item source of the event.
     *  @return item name.
     */
    public String getItemName() {
        return this.itemName;
    }

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/

}
